on:
  push:
    branches:
      - main
  workflow_dispatch:
name: Release-please
jobs:
  release-please:
    permissions:
       contents: write 
       pull-requests: write 
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
      - name: Trigger Build and Publish Workflow
        if: ${{ steps.release.outputs.release_created }}
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.MY_PAT }}
          repository: elyeandre/streamely-native-app
          event-type: build-project 
          client-payload: '{"upload_url": "${{ steps.release.outputs.upload_url }}", "tag_name": "${{ steps.release.outputs.tag_name }}" }'     
